### ISSUE TITLE
Travis-CI access

### ISSUE THREAD

**Issue by ocefpaf** [conda-forge/esmpy-feedstock#1]
The team was created but I still don't have access to Travis-CI here.  That is weird :worried:

**Comment by pelson** [comment]
> The team was created but I still don't have access to Travis-CI here. That is weird :worried:

(and concerning)

Yes. Especially you @ocefpaf as you are an administrator on the whole forge organisation. If it doesn't work for you, it really *isn't* going to work for a non-administrator. The thing is, I don't really understand how I have access but you don't. The travis-ci hook has been registered by the conda-forge-admin user, not me, so I should be in exactly the same position as you - but I'm not, I do have a restart button...

**Comment by ocefpaf** [comment]
>  If it doesn't work for you, it really isn't going to work for a non-administrator.

I guess it was a temporary glitch in Travis-CI.  I had access automatically in the others feedstocks, even before conda-forge.io finished its job, and I have here today.
