### ISSUE TITLE
Compatibility with esmf v7.1

### ISSUE THREAD

**Issue by alicebarthel** [conda-forge/esmpy-feedstock#11]
My project required ESMpy and ESMF.
1) Esmf was installed with another package (nco?) through conda-forge.

2) I then installed esmpy through conda-forge
conda install -c conda-forge esmpy

3) I could not run the HelloWorld test due to a linking problem
AttributeError: User/miniconda2/lib/libesmf_fullylinked.so: undefined symbol: ESMC_InterfaceIntSet

4) Problem was resolved by downgrading esmf:
conda install -c conda-forge esmf=7.0.0

However, it took me a while to figure out what the problem was (the default esmf installed was v7.1), and I did not see any notes on the ESMF-ESMPy website, or on conda-forge mentioning this issue. Can it at least be flagged to save other users' time?

**Comment by bekozi** [comment]
The new ESMF release is `v7.1.0r`. There has been some complications getting the new version to build properly on `conda-forge`. Sorry, for the trouble. It should be resolved soon.

**Comment by bekozi** [comment]
@alicebarthel This should be resolved in `conda-forge` now. Let me know if you continue to have issues.
