### ISSUE TITLE
Circle CI builds?

### ISSUE THREAD

**Issue by bekozi** [conda-forge/esmpy-feedstock#13]
@ocefpaf, @CJ-Wright 

I'm not sure how to proceed with these builds. They work on the PR, but when I merge everything bails out. It's probably user error on this end, but I'm currently at a loss. What do you suggest?

https://circleci.com/gh/conda-forge/esmpy-feedstock/34

**Comment by ocefpaf** [comment]
I'll updated the token. We left this as-is just so we could have a data point to create an automated way to do that, but we can find another feedstock for this. Let's get the new version out there!

**Comment by bekozi** [comment]
Thanks! Will try again.

**Comment by ocefpaf** [comment]
No need. I restarted CircleCI and the latest package is already in the channel.

**Comment by bekozi** [comment]
Oops, you're right. Misread the version numbers. All good then!

**Comment by bekozi** [comment]
Yes, this version is okay. I don't think there are any outstanding issues on the `xESMF` side.

**Comment by ocefpaf** [comment]
Thanks. I'll give it a try today.
