### ISSUE TITLE
missing packages

### ISSUE THREAD

**Issue by doutriaux1** [conda-forge/esmpy-feedstock#16]
only linux py2 and osx py3 are available

I was expecting to also see linux py3 and osx py2

see: 
https://anaconda.org/conda-forge/esmpy/files

**Comment by bekozi** [comment]
@ocefpaf Sorry to drag you into this again, but I'm not sure what happened to the missing packages. I know we are building all of them. Should I kick off a new set of builds?

**Comment by bekozi** [comment]
@doutriaux1 We have the full suite of packages available on our NESII Anaconda.org site: https://anaconda.org/NESII/esmpy/files. We build these against `conda-forge` packages, so `-c nesii -c conda-forge`.

**Comment by dnadeau4** [comment]
@bekozi we cannot add another channel in conda-forge recipes.   We do it in our own recipe though.

**Comment by doutriaux1** [comment]
@bekozi yes we do that for now, but i was really excited to see 7.1 in conda-forge

**Comment by bekozi** [comment]
Yeah, so was I, but we've been having issues getting these built. :worried: Thought it was resolved, so now we're back on it. Sorry for the trouble...

**Comment by dnadeau4** [comment]
@bekozi If you write this comment "@conda-forge-admin, please rerender" in your PR,  it will restart.  (You might need to create a new PR with a new build number.)

example:
https://github.com/conda-forge/libcdms-feedstock/pull/8

The build and rerender the conda-recipe.  I looked at your build and everthing worked, but it seems that when you merged the script to upload did not work properly.

**Comment by dnadeau4** [comment]
https://conda-forge.org/docs/webservice.html

**Comment by ocefpaf** [comment]
Rerendering should do it. I am traveling now but I'll take a closer look as
soon as I get back.

**Comment by bekozi** [comment]
It's definitely during the upload phase, so if rerendering will fix it, good. I think @ocefpaf did this recently, so it may not be the golden ticket unfortunately.

**Comment by ocefpaf** [comment]
PR #18 worked and all the packages are in the channel now:

https://anaconda.org/conda-forge/esmpy/files

**Comment by bekozi** [comment]
Thanks @ocefpaf. I'm not sure I fully follow why the testing setup was breaking the upload, but I'm of course glad to see this resolved. 

@doutriaux1 or @dnadeau4 hopefully everything is good on your end now.

**Comment by ocefpaf** [comment]
> I'm not sure I fully follow why the testing setup was breaking the upload

Neither do I :smile: 

It has happened before in other circumstances, like https://github.com/conda-forge/nco-feedstock/blob/master/recipe/run_test.sh#L28
