### ISSUE TITLE
version numbering for ESMPy (e.g. 7.1.0r) causes problems with conda 4.6.*

### ISSUE THREAD

**Issue by xylar** [conda-forge/esmpy-feedstock#21]
Just as with ESMF, the non-standard `r` at the end of the version number is not compatible with [PEP 440](https://www.python.org/dev/peps/pep-0440), used by conda to parse the syntax of version numbers.  The trailing `r` is treated like an `a` or `b` to indicate a pre-release version.

See https://github.com/conda-forge/esmf-feedstock/issues/35

**Comment by xylar** [comment]
@bekozi, @ocefpaf and @rokuingh, I apologize for not mentioning this yesterday along with my issue on `esmf`.

**Comment by ocefpaf** [comment]
> See [conda-forge/esmf-feedstock#35](https://github.com/conda-forge/esmf-feedstock/issues/35)

Let's merge https://github.com/conda-forge/esmf-feedstock/issues/35 first and then I'll fix this one here to ensure the right `esmf` will be picked up in the package metadata.

**Comment by xylar** [comment]
Great, that makes perfect sense.
