### ISSUE TITLE
ESMPy release 8.0.0

### ISSUE THREAD

**Issue by JiaweiZhuang** [conda-forge/esmpy-feedstock#26]
I notice that ESMF 8.0.0 was added by conda-forge/esmf-feedstock#43. Further adding ESMPy 8.0.0 would resolve JiaweiZhuang/xESMF#11 😀 

It is just a matter of updating this block I think?

https://github.com/conda-forge/esmpy-feedstock/blob/8d43d82bc2919d1202fbe6576826b67d97b2db03/recipe/meta.yaml#L1-L11

The new URL is `http://www.earthsystemmodeling.org/esmf_releases/public/ESMF_8_0_0/esmf_8_0_0_src.tar.gz`, so the updates would be:

- `version = "7.1.0"` -> `version = "8.0.0"`
- `ver = version.replace(".", "_") + "r"` -> `ver = version.replace(".", "_")`  (without the `r`)
- sha256: `75c34c41806e703551b6b79566edf34c23f1eebcf821749e5320e860e565d94f`

**Comment by ocefpaf** [comment]
Yep. That is what would take to update it. I believe that @bekozi is on it. See #25 and #23

**Comment by JiaweiZhuang** [comment]
Oh great! I didn't notice the PRs. Thanks @bekozi for working on it!!

**Comment by bekozi** [comment]
Bumped version: https://github.com/conda-forge/esmpy-feedstock/pull/27.
