### ISSUE TITLE
snapshots 32 and 33 are on main label

### ISSUE THREAD

**Issue by xylar** [conda-forge/esmpy-feedstock#36]
They should be on the `esmpy_dev` label

**Comment by xylar** [comment]
@ocefpaf, do you know what I might have done wrong in #34?  It seems like the same problem must have happened in https://github.com/conda-forge/esmf-feedstock/pull/56 because those packages ended up on the `main` label, too. Very sorry about that.

**Comment by xylar** [comment]
I think I'm using old syntax.  It should be like https://conda-forge.org/docs/maintainer/conda_forge_yml.html#channels

Shoot, @ocefpaf, can you clean up my mess by moving all those packages to the appropriate `esmf_dev` or `esmpy_dev` labels?  I'll fix the `dev` branches.

**Comment by xylar** [comment]
Okay, so the mistake in https://github.com/conda-forge/esmf-feedstock/pull/56 was not having `channel_sources`, hopefully fixed in https://github.com/conda-forge/esmf-feedstock/pull/58 (rerender looks good).  

The mistake in #34 was just a really dumb one -- I didn't rerender after adding the `channel_sources` and `channel_targets` :-(.  Should be fixed in #37

**Comment by xylar** [comment]
@ocefpaf, thanks so much for cleaning up this mess!

**Comment by ocefpaf** [comment]
No problem. I did that so many times in the past. All the dev releases guides are quite new.
