### ISSUE TITLE
Broken docs links and installing without conda

### ISSUE THREAD

**Issue by gcaria** [conda-forge/esmpy-feedstock#45]
Hi,

I am trying to install esmpy, but avoiding conda since I don't use it. What's the suggested procedure in this case?

I've tried to open the ESMF User’s Guide [link](http://earthsystemmodeling.org/esmf_releases/non_public/ESMF_8_0_0/ESMF_usrdoc/) in the docs, but it takes me nowhere.

(also this link seems to not work [ESMPy Download page.](http://www.earthsystemcog.org/projects/esmpy/releases))

**Comment by xylar** [comment]
@gcaria, this is the page for making `esmpy` for `conda`, so if you don't want to use `conda`, I'm afraid you will need to contact the ESMF folks about that: http://earthsystemmodeling.org/esmpy/

**Comment by rokuingh** [comment]
@gcarla I apologize for the broken links. Please refer to the [ESMPy documentation from the latest ESMF 8.1.0 release](http://earthsystemmodeling.org/esmpy_doc/release/ESMF_8_1_0/html/install.html). This should have correct links to the ESMF user's guide, as well as instructions on how to build ESMPy from source.
