### ISSUE TITLE
On update to >8.1.1, remove patch to setup.py

### ISSUE THREAD

**Issue by zklaus** [conda-forge/esmpy-feedstock#50]
- [x] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue:

The tarball of version 8.1.1 still had version 8.1.0 in the setup.py of esmpy, leading to the current patch. For the next version, this patch most likely has to be removed.

This issue serves merely as a reminder/clarification and can be closed after the next release.

**Comment by xylar** [comment]
This patch was removed in #51
