### ISSUE TITLE
Dependency on pytest-json-report

### ISSUE THREAD

**Issue by maresb** [conda-forge/esmpy-feedstock#74]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

```Dockerfile
FROM mambaorg/micromamba

RUN micromamba install -y -c conda-forge -n base esmpy pip
ARG MAMBA_DOCKERFILE_ACTIVATE=1
RUN pip check
```

Result:
```
esmpy 8.4.2 requires pytest-json-report, which is not installed.
```

### Installed packages

```shell
.
```

### Environment info

```shell
.
```

**Comment by maresb** [comment]
Hmm, seems to be [upstream](https://github.com/esmf-org/esmf/blob/v8.4.2/src/addon/esmpy/pyproject.toml)

**Comment by zklaus** [comment]
It may be already upstream, but that doesn't mean we can't fix it here :) I'll give it a stab.
