### ISSUE TITLE
Python 3

### ISSUE THREAD

**Issue by ocefpaf** [conda-forge/esmpy-feedstock#8]
@JiaweiZhuang asked in https://github.com/pydata/xarray/issues/486#issuecomment-325998681

> @ocefpaf Any plan for Python3-compatible ESMPy? I only see Python2.7 here: https://github.com/conda-forge/esmpy-feedstock

@bekozi is there a py3k version released? I confess I lost track of the package (using mostly the `nco` wrapped version :smile:)

**Comment by bekozi** [comment]
Good morning. There is a Python 3.5/3.6 version of ESMPy available in our group's `dev-esmf` Anaconda channel: https://anaconda.org/nesii/repo/files?type=any&label=dev-esmf. Once there is an official ESMF release the conda-forge channel can be updated - not sure when that will be.

**Comment by ocefpaf** [comment]
We can put the dev in conda-forge under a label like `main/dev` to make it easier for users and avoid multiple channels. If you are interested in that let me know and we can try it here.

**Comment by bekozi** [comment]
Sure, no issues with that on this end. We'll probably continue to maintain our channel regardless, but it makes sense to simplify channel requirements. ESMF is on a pretty slow release cycle but has a strong test harness. Hence, it would be great to get beta snapshots out there if possible!

**Comment by ocefpaf** [comment]
>  We'll probably continue to maintain our channel regardless

Sure. One of the goals of `conda-forge` is not to substitute all other channels, but to share recipes and keep them in sync (although that sometimes is quite the challenge).

I'll take a look into updating the recipe here and adding the `dev` label later today.

**Comment by bekozi** [comment]
> although that sometimes is quite the challenge

Doing great from what I can tell.

Thanks for making the initial changes.

**Comment by JiaweiZhuang** [comment]
@bekozi Great! It would be very useful to support Mac (I know Windows is tricker).

On the [ESMPy website](https://www.earthsystemcog.org/projects/esmpy/conda) I can only find:
- On conda-forge, only Python2.7, but include Linux and Mac
- On NESII, include Python2.7, 3.5, 3.6, but only Linux

**Comment by bekozi** [comment]
> It would be very useful to support Mac (I know Windows is tricker).

Once the development builds are enabled in conda-forge Mac + Python 3 will be supported. You are correct that Windows is trickier. :smile: We support MingW and Cygwin. I know of an effort to get ESMF running in Windows natively. If that project bears fruit and makes it back into ESMF, it will definitely be pushed upstream!

**Comment by jhamman** [comment]
@bekozi - did this ever get resolved? Would love to see this get finalized in conda-forge if possible.

**Comment by bekozi** [comment]
It is nearly, nearly there. https://github.com/conda-forge/esmpy-feedstock/pull/10 will take care of it in `conda-forge`. In the meantime, there are Python 3 builds in `-c nesii -c conda-forge`.

**Comment by bekozi** [comment]
Python 3 builds for `ESMPy` are in.
