### ISSUE TITLE
Activate scripts can be missing following #77

### ISSUE THREAD

**Issue by zklaus** [conda-forge/esmpy-feedstock#80]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

With #77, we removed the de-/activate scripts because they are now in the esmf package. However, the esmpy package without the scripts can still pull in esmf packages *without* the scripts, for example, we got an environment with
```
# Name                    Version                   Build  Channel
esmf                      8.4.2           nompi_h20110ff_0    conda-forge
esmpy                     8.4.2              pyhc1e730c_2    conda-forge
```
where the earliest esmf package with the scripts is build number 2.

I am not sure how to address this. Perhaps it's best to undo this change and make it coincide with the next version shift? Or we could pull the esmf package builds for version 8.4.2 without the scripts.

@xylar, what do you think? Imho, this is a rather high priority issue.

### Installed packages

```shell
-
```

### Environment info

```shell
-
```

**Comment by xylar** [comment]
Okay, we can revert the removal of the activation scripts.  I had assumed that the higher build number would be prioritized for `esmf` but that won't be true if you're trying to use an older `hdf5`.

**Comment by zklaus** [comment]
Perhaps it would be easiest to pull the esmf-8.4.2 builds <2? Or can we add a run_constrained in a repodata patch? In that case we could patch the the earlier esmf builds to exclude prevent the newer esmpy builds.

**Comment by xylar** [comment]
I don't think that's a good idea to pull the esmf packages.  It could leave certain configurations with the earlier hdf5 completely unsolvable.  And I think a repopatch might have the same issue.  Plus, I'm not clear on whether it is possible to have a repopatch that constraints to specific builds.  That is certainly unusual.

**Comment by xylar** [comment]
Maybe the best fix would be to pull the most recent build that removed the activate/deactivate scripts but I think it will be good enough to just revert the PR in #81.  There should be no reason that #77 gets priority over #81 by the package solver.  We could always mark the packages from #77 as broken if they are causing trouble.
