### ISSUE TITLE
Unify version number for pip and conda

### ISSUE THREAD

**Issue by JiaweiZhuang** [conda-forge/esmpy-feedstock#9]
I installed the `7.1.0.dev38` version by 
```
conda install -c nesii/label/dev-esmf -c conda-forge esmpy==7.1.0.dev38
```

`conda list` does show the correct version number

```
$conda list esmpy
esmpy                     7.1.0.dev38              py36_1    nesii/label/dev-esmf
```

But `pip show` says the version is `7.1.0.dev0`

```
$pip show esmpy
Name: ESMPy
Version: 7.1.0.dev0
Summary: ESMF Python interface
...
```

I would like a consistent version number for pip so that I can correctly specify the dependency for [xESMF](https://github.com/JiaweiZhuang/xESMF) in setup.py:

```
setup(...
      install_requires=['esmpy==7.1.0.dev38', ...]
      )
```

Currently I need to write `'esmpy==7.1.0.dev0'`, but that's dangerous because ESMPy can only write offline weights after `dev38`. Due to the complicated software dependency (xESMF -> ESMPy -> ESMF) I want to take version checking and continuous integration seriously 😅

**Comment by bekozi** [comment]
The new `ESMPy` builds will have the right version number. However, once dev builds are needed the versions will go back to something like `8.0.0dev0`. I'm going to close this, but let me know if there is still anything amiss.
